// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YTPlaylistSearcherWebApp.Data;
using YTPlaylistSearcherWebApp.Models;

#nullable disable

namespace YTPlaylistSearcherWebApp.Data.Configurations
{
    public partial class HoneymediaConfiguration : IEntityTypeConfiguration<Honeymedia>
    {
        public void Configure(EntityTypeBuilder<Honeymedia> entity)
        {
            entity.ToTable("honeymedia");

            entity.HasIndex(e => e.Id, "ID_UNIQUE")
                .IsUnique();

            entity.HasIndex(e => e.InterestTypeId, "media_interest_idx");

            entity.HasIndex(e => e.ResponseId, "media_response_idx");

            entity.HasIndex(e => e.StatusId, "media_status_idx");

            entity.HasIndex(e => e.MediaTypeId, "media_types_idx");

            entity.HasIndex(e => e.RequestingUserId, "media_user_idx");

            entity.Property(e => e.AaronComment).HasMaxLength(500);

            entity.Property(e => e.DateFinished).HasColumnType("datetime");

            entity.Property(e => e.DateRequested).HasColumnType("datetime");

            entity.Property(e => e.LastUpdated).HasColumnType("datetime");

            entity.Property(e => e.MediaTitle).HasMaxLength(250);

            entity.Property(e => e.NoelleComment).HasMaxLength(500);

            entity.Property(e => e.Pitch).HasMaxLength(250);

            entity.Property(e => e.Tracker).HasMaxLength(500);

            entity.HasOne(d => d.InterestType)
                .WithMany(p => p.Honeymedia)
                .HasForeignKey(d => d.InterestTypeId)
                .HasConstraintName("media_interest");

            entity.HasOne(d => d.MediaType)
                .WithMany(p => p.Honeymedia)
                .HasForeignKey(d => d.MediaTypeId)
                .HasConstraintName("media_types");

            entity.HasOne(d => d.RequestingUser)
                .WithMany(p => p.Honeymedia)
                .HasForeignKey(d => d.RequestingUserId)
                .HasConstraintName("media_user");

            entity.HasOne(d => d.Response)
                .WithMany(p => p.Honeymedia)
                .HasForeignKey(d => d.ResponseId)
                .HasConstraintName("media_response");

            entity.HasOne(d => d.Status)
                .WithMany(p => p.Honeymedia)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("media_status");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Honeymedia> entity);
    }
}
