// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YTPlaylistSearcherWebApp.Data;
using YTPlaylistSearcherWebApp.Models;

#nullable disable

namespace YTPlaylistSearcherWebApp.Data.Configurations
{
    public partial class MediainterestConfiguration : IEntityTypeConfiguration<Mediainterest>
    {
        public void Configure(EntityTypeBuilder<Mediainterest> entity)
        {
            entity.ToTable("mediainterest");

            entity.HasIndex(e => e.Id, "Id_UNIQUE")
                .IsUnique();

            entity.Property(e => e.Color).HasMaxLength(45);

            entity.Property(e => e.InterestTypeName).HasMaxLength(45);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Mediainterest> entity);
    }
}
