// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YTPlaylistSearcherWebApp.Data;
using YTPlaylistSearcherWebApp.Models;

#nullable disable

namespace YTPlaylistSearcherWebApp.Data.Configurations
{
    public partial class MediarequesterConfiguration : IEntityTypeConfiguration<Mediarequester>
    {
        public void Configure(EntityTypeBuilder<Mediarequester> entity)
        {
            entity.ToTable("mediarequester");

            entity.HasIndex(e => e.Id, "Id_UNIQUE")
                .IsUnique();

            entity.Property(e => e.Name).HasMaxLength(45);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Mediarequester> entity);
    }
}
