// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YTPlaylistSearcherWebApp.Data;
using YTPlaylistSearcherWebApp.Models;

#nullable disable

namespace YTPlaylistSearcherWebApp.Data.Configurations
{
    public partial class PlaylistvideoConfiguration : IEntityTypeConfiguration<Playlistvideo>
    {
        public void Configure(EntityTypeBuilder<Playlistvideo> entity)
        {
            entity.HasKey(e => new { e.PlaylistId, e.VideoId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.ToTable("playlistvideos");

            entity.HasIndex(e => e.VideoId, "playlistvideos_videos_idx");

            entity.Property(e => e.PlaylistId).HasColumnName("playlistID");

            entity.Property(e => e.VideoId).HasColumnName("videoID");

            entity.Property(e => e.AddedDate)
                .HasColumnType("datetime")
                .HasColumnName("addedDate");

            entity.HasOne(d => d.Playlist)
                .WithMany(p => p.Playlistvideos)
                .HasForeignKey(d => d.PlaylistId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("playlistvideos_playlist");

            entity.HasOne(d => d.Video)
                .WithMany(p => p.Playlistvideos)
                .HasForeignKey(d => d.VideoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("playlistvideos_videos");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Playlistvideo> entity);
    }
}
