// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YTPlaylistSearcherWebApp.Data;
using YTPlaylistSearcherWebApp.Models;

#nullable disable

namespace YTPlaylistSearcherWebApp.Data.Configurations
{
    public partial class PlaylistsearchhistoryConfiguration : IEntityTypeConfiguration<Playlistsearchhistory>
    {
        public void Configure(EntityTypeBuilder<Playlistsearchhistory> entity)
        {
            entity.ToTable("playlistsearchhistories");

            entity.HasIndex(e => e.PlaylistId, "FK_SearchHistory_Playlist_ID_idx");

            entity.HasIndex(e => e.UserId, "FK_SearchHistory_User_ID_idx");

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("createdDate");

            entity.Property(e => e.PlaylistId).HasColumnName("playlistID");

            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.HasOne(d => d.Playlist)
                .WithMany(p => p.Playlistsearchhistories)
                .HasForeignKey(d => d.PlaylistId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SearchHistory_Playlist_ID");

            entity.HasOne(d => d.User)
                .WithMany(p => p.Playlistsearchhistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SearchHistory_User_ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Playlistsearchhistory> entity);
    }
}
