// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YTPlaylistSearcherWebApp.Data;
using YTPlaylistSearcherWebApp.Models;

#nullable disable

namespace YTPlaylistSearcherWebApp.Data.Configurations
{
    public partial class RolepolicyConfiguration : IEntityTypeConfiguration<Rolepolicy>
    {
        public void Configure(EntityTypeBuilder<Rolepolicy> entity)
        {
            entity.ToTable("rolepolicies");

            entity.HasIndex(e => e.Id, "ID_UNIQUE")
                .IsUnique();

            entity.HasIndex(e => e.Policy, "rolepolicies_policy_id_idx");

            entity.HasIndex(e => e.Role, "rolepolicies_role_id_idx");

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Policy).HasColumnName("policy");

            entity.Property(e => e.Role).HasColumnName("role");

            entity.HasOne(d => d.PolicyNavigation)
                .WithMany(p => p.Rolepolicies)
                .HasForeignKey(d => d.Policy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("rolepolicies_policy_id");

            entity.HasOne(d => d.RoleNavigation)
                .WithMany(p => p.Rolepolicies)
                .HasForeignKey(d => d.Role)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("rolepolicies_role_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Rolepolicy> entity);
    }
}
