// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YTPlaylistSearcherWebApp.Data;
using YTPlaylistSearcherWebApp.Models;

#nullable disable

namespace YTPlaylistSearcherWebApp.Data.Configurations
{
    public partial class UserauthenticationConfiguration : IEntityTypeConfiguration<Userauthentication>
    {
        public void Configure(EntityTypeBuilder<Userauthentication> entity)
        {
            entity.ToTable("userauthentications");

            entity.HasIndex(e => e.Id, "ID_UNIQUE")
                .IsUnique();

            entity.HasIndex(e => e.Password, "password_UNIQUE")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.LastUpdated)
                .HasColumnType("datetime")
                .HasColumnName("lastUpdated")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.Property(e => e.Password)
                .HasMaxLength(200)
                .HasColumnName("password");

            entity.Property(e => e.PasswordSalt)
                .HasMaxLength(200)
                .HasColumnName("passwordSalt");

            entity.Property(e => e.RecoveryCode)
                .HasMaxLength(10)
                .HasColumnName("recoveryCode");

            entity.Property(e => e.RefreshDate)
                .HasColumnType("datetime")
                .HasColumnName("refreshDate");

            entity.Property(e => e.RefreshToken)
                .HasMaxLength(100)
                .HasColumnName("refreshToken");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Userauthentication> entity);
    }
}
