// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using YTPlaylistSearcherWebApp.Data;
using YTPlaylistSearcherWebApp.Models;

#nullable disable

namespace YTPlaylistSearcherWebApp.Data.Configurations
{
    public partial class VideocommentConfiguration : IEntityTypeConfiguration<Videocomment>
    {
        public void Configure(EntityTypeBuilder<Videocomment> entity)
        {
            entity.ToTable("videocomments");

            entity.HasIndex(e => e.UserId, "FK_VideoComments_Users_ID_idx");

            entity.HasIndex(e => e.VideoId, "FK_VideoComments_Videos_ID_idx");

            entity.HasIndex(e => e.Id, "ID_UNIQUE")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Comment)
                .HasMaxLength(500)
                .HasColumnName("comment");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("createdDate");

            entity.Property(e => e.MembersOnly)
                .HasColumnName("membersOnly")
                .HasDefaultValueSql("'1'");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasColumnName("modifiedDate");

            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.Property(e => e.VideoId).HasColumnName("videoID");

            entity.HasOne(d => d.User)
                .WithMany(p => p.Videocomments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VideoComments_Users_ID");

            entity.HasOne(d => d.Video)
                .WithMany(p => p.Videocomments)
                .HasForeignKey(d => d.VideoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VideoComments_Videos_ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Videocomment> entity);
    }
}
