<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <SpaRoot>ClientApp\</SpaRoot>
    <SpaProxyServerUrl>https://localhost:44422</SpaProxyServerUrl>
    <SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a9e6910b-554c-4b62-a457-151b05fed61d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="6.0.33" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="6.0.16" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <!-- Don't publish the SPA source files, but do show them in the project files list -->
    <Content Remove="$(SpaRoot)**" />
    <None Remove="$(SpaRoot)**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DTOs\YTPlaylistVideo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Build\builds.data" />
    <Content Remove="wwwroot\Build\builds.framework.js" />
    <Content Remove="wwwroot\Build\builds.loader.js" />
    <Content Remove="wwwroot\Build\builds.wasm" />
    <Content Remove="wwwroot\index.html" />
    <Content Remove="wwwroot\TemplateData\favicon.ico" />
    <Content Remove="wwwroot\TemplateData\fullscreen-button.png" />
    <Content Remove="wwwroot\TemplateData\progress-bar-empty-dark.png" />
    <Content Remove="wwwroot\TemplateData\progress-bar-empty-light.png" />
    <Content Remove="wwwroot\TemplateData\progress-bar-full-dark.png" />
    <Content Remove="wwwroot\TemplateData\progress-bar-full-light.png" />
    <Content Remove="wwwroot\TemplateData\style.css" />
    <Content Remove="wwwroot\TemplateData\unity-logo-dark.png" />
    <Content Remove="wwwroot\TemplateData\unity-logo-light.png" />
    <Content Remove="wwwroot\TemplateData\webgl-logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Build\builds.data" />
    <None Include="wwwroot\Build\builds.framework.js" />
    <None Include="wwwroot\Build\builds.loader.js" />
    <None Include="wwwroot\Build\builds.wasm" />
    <None Include="wwwroot\index.html" />
    <None Include="wwwroot\TemplateData\favicon.ico" />
    <None Include="wwwroot\TemplateData\fullscreen-button.png" />
    <None Include="wwwroot\TemplateData\progress-bar-empty-dark.png" />
    <None Include="wwwroot\TemplateData\progress-bar-empty-light.png" />
    <None Include="wwwroot\TemplateData\progress-bar-full-dark.png" />
    <None Include="wwwroot\TemplateData\progress-bar-full-light.png" />
    <None Include="wwwroot\TemplateData\style.css" />
    <None Include="wwwroot\TemplateData\unity-logo-dark.png" />
    <None Include="wwwroot\TemplateData\unity-logo-light.png" />
    <None Include="wwwroot\TemplateData\webgl-logo.png" />
  </ItemGroup>

    <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>
  
  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --configuration production" />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)dist\**; $(SpaRoot)dist-server\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>wwwroot\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
