// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class Honeymedia
    {
        public int Id { get; set; }
        public string MediaTitle { get; set; } = null!;
        public string? Pitch { get; set; }
        public int? MediaTypeId { get; set; }
        public int? InterestTypeId { get; set; }
        public int? RequestingUserId { get; set; }
        public int? ResponseId { get; set; }
        public int? StatusId { get; set; }
        public int? NoelleRating { get; set; }
        public int? AaronRating { get; set; }
        public string? NoelleComment { get; set; }
        public string? AaronComment { get; set; }
        public string? Tracker { get; set; }
        public DateTime? DateRequested { get; set; }
        public DateTime? DateFinished { get; set; }
        public DateTime? LastUpdated { get; set; }

        public virtual Mediainterest? InterestType { get; set; }
        public virtual Mediatype? MediaType { get; set; }
        public virtual Mediarequester? RequestingUser { get; set; }
        public virtual Mediaresponse? Response { get; set; }
        public virtual Mediastatus? Status { get; set; }
    }
}