// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class Mediaresponse
    {
        public Mediaresponse()
        {
            Honeymedia = new HashSet<Honeymedia>();
        }

        public int Id { get; set; }
        public string? Response { get; set; }

        public virtual ICollection<Honeymedia> Honeymedia { get; set; }
    }
}