// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class Playlistvideo
    {
        public int PlaylistId { get; set; }
        public int VideoId { get; set; }
        public DateTime? AddedDate { get; set; }

        public virtual Playlist Playlist { get; set; } = null!;
        public virtual Video Video { get; set; } = null!;
    }
}