// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class Policy
    {
        public Policy()
        {
            Rolepolicies = new HashSet<Rolepolicy>();
        }

        public int Id { get; set; }
        public string? PolicyName { get; set; }

        public virtual ICollection<Rolepolicy> Rolepolicies { get; set; }
    }
}