// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class Role
    {
        public Role()
        {
            Rolepolicies = new HashSet<Rolepolicy>();
            Users = new HashSet<User>();
        }

        public int Id { get; set; }
        public string? RoleName { get; set; }

        public virtual ICollection<Rolepolicy> Rolepolicies { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}