// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class Rolepolicy
    {
        public int Id { get; set; }
        public int Role { get; set; }
        public int Policy { get; set; }

        public virtual Policy PolicyNavigation { get; set; } = null!;
        public virtual Role RoleNavigation { get; set; } = null!;
    }
}