// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class Sharedpost
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string? Content { get; set; }
        public string? Link { get; set; }
        public string? Thumbnail { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string? Type { get; set; }

        public virtual User User { get; set; } = null!;
    }
}