// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class User
    {
        public User()
        {
            FollowerFolloweeNavigations = new HashSet<Follower>();
            FollowerFollower1Navigations = new HashSet<Follower>();
            Playlistsearchhistories = new HashSet<Playlistsearchhistory>();
            Sharedposts = new HashSet<Sharedpost>();
        }

        public int Id { get; set; }
        public string UserName { get; set; } = null!;
        public string? Email { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? ProfilePicture { get; set; }
        public DateTime RegistrationDate { get; set; }
        public DateTime LastLoginDate { get; set; }
        public int AccountStatus { get; set; }
        public int Role { get; set; }
        public int Authentication { get; set; }

        public virtual Accountstatus AccountStatusNavigation { get; set; } = null!;
        public virtual Userauthentication AuthenticationNavigation { get; set; } = null!;
        public virtual Role RoleNavigation { get; set; } = null!;
        public virtual ICollection<Follower> FollowerFolloweeNavigations { get; set; }
        public virtual ICollection<Follower> FollowerFollower1Navigations { get; set; }
        public virtual ICollection<Playlistsearchhistory> Playlistsearchhistories { get; set; }
        public virtual ICollection<Sharedpost> Sharedposts { get; set; }
    }
}