// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class User
    {
        public int Id { get; set; }
        public string UserName { get; set; } = null!;
        public string? Email { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? ProfilePicture { get; set; }
        public DateTime RegistrationDate { get; set; }
        public DateTime LastLoginDate { get; set; }
        public int AccountStatus { get; set; }
        public int Role { get; set; }
        public int Authentication { get; set; }

        public virtual Accountstatus AccountStatusNavigation { get; set; } = null!;
        public virtual Userauthentication AuthenticationNavigation { get; set; } = null!;
        public virtual Role RoleNavigation { get; set; } = null!;
    }
}