// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class Video
    {
        public int Id { get; set; }
        public string VideoId { get; set; } = null!;
        public string? Title { get; set; }
        public string? ChannelTitle { get; set; }
        public string? Description { get; set; }
        public string? Thumbnail { get; set; }
        public DateTime? PublishedDate { get; set; }
        public int? PlaylistId { get; set; }

        public virtual Playlist? Playlist { get; set; }
    }
}