// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models
{
    public partial class Video
    {
        public Video()
        {
            Playlistvideos = new HashSet<Playlistvideo>();
            Videocomments = new HashSet<Videocomment>();
        }

        public int Id { get; set; }
        public string VideoId { get; set; } = null!;
        public string? Title { get; set; }
        public string? ChannelTitle { get; set; }
        public string? Description { get; set; }
        public string? Thumbnail { get; set; }
        public DateTime? PublishedDate { get; set; }

        public virtual ICollection<Playlistvideo> Playlistvideos { get; set; }
        public virtual ICollection<Videocomment> Videocomments { get; set; }
    }
}