// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models.CS
{
    public partial class Lineup
    {
        public int Id { get; set; }
        public string Path { get; set; } = null!;
        public int GrenadeTypeId { get; set; }
        public int ThrowStyleTypeId { get; set; }
        public int MapId { get; set; }
        public int TeamId { get; set; }
        public string From { get; set; } = null!;
        public string To { get; set; } = null!;

        public virtual Grenadetype GrenadeType { get; set; } = null!;
        public virtual Map Map { get; set; } = null!;
        public virtual Team Team { get; set; } = null!;
        public virtual Throwstyle ThrowStyleType { get; set; } = null!;
    }
}