// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace YTPlaylistSearcherWebApp.Models.CS
{
    public partial class Map
    {
        public Map()
        {
            Lineups = new HashSet<Lineup>();
        }

        public int Id { get; set; }
        public string Slug { get; set; } = null!;
        public string Name { get; set; } = null!;

        public virtual ICollection<Lineup> Lineups { get; set; }
    }
}