// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using YTPlaylistSearcherWebApp.Data.Configurations;
using YTPlaylistSearcherWebApp.Models;
#nullable enable

namespace YTPlaylistSearcherWebApp.Data
{
    public partial class YTPSContext : DbContext
    {
        public YTPSContext()
        {
        }

        public YTPSContext(DbContextOptions<YTPSContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Playlist> Playlists { get; set; } = null!;
        public virtual DbSet<Video> Videos { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("utf8mb4_0900_ai_ci")
                .HasCharSet("utf8mb4");

            modelBuilder.ApplyConfiguration(new Configurations.PlaylistConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VideoConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
