// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using YTPlaylistSearcherWebApp.Models.CS;
#nullable enable

namespace YTPlaylistSearcherWebApp.Data.CS
{
    public partial class CSContext : DbContext
    {
        public CSContext()
        {
        }

        public CSContext(DbContextOptions<CSContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Grenadetype> Grenadetypes { get; set; } = null!;
        public virtual DbSet<Lineup> Lineups { get; set; } = null!;
        public virtual DbSet<Map> Maps { get; set; } = null!;
        public virtual DbSet<Team> Teams { get; set; } = null!;
        public virtual DbSet<Throwstyle> Throwstyles { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("utf8mb4_0900_ai_ci")
                .HasCharSet("utf8mb4");

            modelBuilder.ApplyConfiguration(new Configurations.GrenadetypeConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.LineupConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MapConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TeamConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ThrowstyleConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
